### ISSUE TITLE
Compile ES6 build

### ISSUE THREAD

**Issue by ejb** [kenchris/jakecache#11]
Since Chrome 54 (the latest version at the time of writing) doesn't support some fancy features like `import`, I suggest bundling a dist version of jakecache transpiled into ES5.

(Ps. I fully intend to tackle these issues myself. Just noting them for future reference.)

**Comment by kenchris** [comment]
That is because @auchenberg created a build step:

https://github.com/kenchris/jakecache/blob/master/scripts/build.js

@auchenberg you should have added that to the README.md :-)
