### ISSUE TITLE
Update jackecache on npm

### ISSUE THREAD

**Issue by ejb** [kenchris/jakecache#15]
Thanks for merging my recent pull requests. Could you update the npm release please?

**Comment by kenchris** [comment]
@auchenberg can you do this?

**Comment by auchenberg** [comment]
v1.1.0 published. https://github.com/kenchris/jakecache/releases/tag/v1.1.0

**Comment by ejb** [comment]
Thanks very much. Really appreciate this useful project :)

**Comment by ejb** [comment]
Arg, sorry to be a continued pain, but the `dist/` folder doesn't appear to have been updated in the npm release.

**Comment by kenchris** [comment]
@auchenberg ^

**Comment by auchenberg** [comment]
Ah, sorry about that. Coming up!

**Comment by auchenberg** [comment]
1.1.1 published.

**Comment by ejb** [comment]
Just installed 1.1.1 and... the new stuff is still not in the `dist/` folder. 😰
Are you compiling from an older commit?
